version: "3.8"

services:
  database:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: petstore
    ports:
      - published: 5432
        target: 5432
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./database/init
        target: /docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - published: 8080
        target: 8080
    environment:
      ADMINER_DESIGN: dracula
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  data:
